# Generated by Django 3.1.3 on 2020-12-19 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('b_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=100)),
                ('b_phno', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'buyer',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_address', models.CharField(max_length=200)),
                ('s_phno', models.CharField(max_length=20)),
                ('s_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer')),
            ],
            options={
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapp.seller'),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(editable=False, max_length=128)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.address')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.product')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.seller')),
            ],
            options={
                'db_table': 'orders',
                'unique_together': {('bid', 'pid', 'sid')},
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.product')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.seller')),
            ],
            options={
                'db_table': 'cart',
                'unique_together': {('pid', 'bid')},
            },
        ),
    ]
