# Generated by Django 3.1.3 on 2020-12-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201222_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='s_email',
            new_name='email',
        ),
    ]
