# Generated by Django 3.1.3 on 2020-12-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20201223_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='email',
            new_name='s_email',
        ),
    ]
