# Generated by Django 3.1.3 on 2020-12-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201224_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
