# Generated by Django 3.1.3 on 2020-12-29 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20201228_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 19, 3, 3, 226544)),
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('bid', 'pid', 'sid', 'created_at')},
        ),
    ]
