# Generated by Django 3.1.3 on 2020-12-29 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20201229_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 20, 18, 54, 759696)),
        ),
    ]
